### ISSUE TITLE
找不到RongCloud/RongCloud class

### ISSUE THREAD

**Issue by longerhot** [rongcloud/server-sdk-php-composer#12]
composer 下载下来的会出现找不到RongCloud/RongCloud class

需要将 vendor 下面的 rongcloud.php 改成 RongCloud.php 才行。
这个是什么原因？

**Comment by yankewei** [comment]
@August2012 因为linux下区分大小写的，既然你用的是composer，那就是自动加载，自动加载的机制是根据文件的命名来的，具体的可以看[类的自动加载](http://php.net/manual/zh/language.oop5.autoload.php)，所以如果开发环境是windows的话，就不会有这个问题，linux下就会出现这个问题
