### ISSUE TITLE
composer 无法安装报错

### ISSUE THREAD

**Issue by newjcj** [rongcloud/server-sdk-php-composer#19]
composer 无法安装报错

**Comment by hejinyu110** [comment]
https://docs.phpcomposer.com/00-intro.html
可以使用链接中的集成方式
如果有报错，您这边将报错的详细信息贴一下

**Comment by newjcj** [comment]
好像是include报错,还有session_start()报错,我自己重新封装了composer包

**Comment by newjcj** [comment]
'serverDispatcher' => [
      'middlewares' => [
          // ...
          \Swoft\Devtool\Middleware\DevToolMiddleware::class,
      ]
  ],
这个中间件是不是应该是 \Swoft\Devtool\Http\Middleware\DevToolMiddleware::class,
