### ISSUE TITLE
laravel5.8框架找不到RongCloud类

### ISSUE THREAD

**Issue by chenzi** [rongcloud/server-sdk-php-composer#20]
![WX20190729-180100](https://user-images.githubusercontent.com/5486633/62039793-eca33400-b22a-11e9-8b9c-2af7ba2aaf02.png)

**Comment by hejinyu110** [comment]
https://docs.phpcomposer.com/00-intro.html
可以使用链接中的集成方式
如果有报错，您这边将报错的详细信息贴一下

**Comment by chenzi** [comment]
就是用的composer安装的， 错误信息就是我发的图片。 后面没办法自己用原始的办法请求的。
